#!/usr/bin/env bash
# Regenerates docs/er-schema.mmd from the Flyway migrations via mermerd.
#
# The committed file is a golden artifact: CI (er-drift job) re-runs this script
# and fails if the output differs — a schema change must regenerate the diagram
# in the same PR. Run locally after adding/changing a migration:
#
#   ./scripts/regen-er.sh
#
# Requires: docker, curl. mermerd is downloaded (pinned) on first use.
set -euo pipefail

MERMERD_VERSION="0.13.0"
PG_IMAGE="postgres:18"
PG_PORT="55432"
OUT_FILE="docs/er-schema.mmd"

cd "$(dirname "$0")/.."

# --- mermerd (pinned, cached in .cache/) ---
os=$(uname -s | tr '[:upper:]' '[:lower:]')
arch=$(uname -m); [[ "$arch" == "x86_64" ]] && arch="amd64"; [[ "$arch" == "aarch64" ]] && arch="arm64"
mermerd=".cache/mermerd-${MERMERD_VERSION}"
if [[ ! -x "$mermerd" ]]; then
  mkdir -p .cache
  curl -sfL "https://github.com/KarnerTh/mermerd/releases/download/v${MERMERD_VERSION}/mermerd_${MERMERD_VERSION}_${os}_${arch}.tar.gz" \
    | tar -xz -C .cache mermerd
  mv .cache/mermerd "$mermerd"
fi

# --- throwaway Postgres with the Flyway schema ---
container=$(docker run -d --rm -e POSTGRES_USER=guestgraph -e POSTGRES_PASSWORD=guestgraph \
  -e POSTGRES_DB=guestgraph -p "${PG_PORT}:5432" "$PG_IMAGE")
trap 'docker stop "$container" >/dev/null' EXIT

echo "waiting for postgres..."
for _ in $(seq 1 60); do
  docker exec "$container" pg_isready -U guestgraph -d guestgraph >/dev/null 2>&1 && break
  sleep 0.5
done

# Apply migrations in Flyway version order (V1, V2, ... — sort -V handles V10 correctly)
for f in $(ls src/main/resources/db/migration/V*.sql | sort -V); do
  echo "applying $f"
  docker exec -i "$container" psql -q -v ON_ERROR_STOP=1 -U guestgraph -d guestgraph < "$f"
done

# --- generate ---
"$mermerd" -c "postgresql://guestgraph:guestgraph@localhost:${PG_PORT}/guestgraph" \
  -s public --useAllTables --showAllConstraints -o "$OUT_FILE"

# Prepend provenance header (mermerd output is a plain .mmd mermaid file)
tmp=$(mktemp)
{
  echo "%% GENERATED by scripts/regen-er.sh (mermerd ${MERMERD_VERSION}) from src/main/resources/db/migration/"
  echo "%% Do not edit by hand — CI fails on drift. Regenerate: ./scripts/regen-er.sh"
  cat "$OUT_FILE"
} > "$tmp" && mv "$tmp" "$OUT_FILE"

echo "wrote $OUT_FILE"
